services:
  web:
    # start with `docker-compose --profile local up`
    profiles: [local]
    build:
      context: .
      args:
        - VERSION=local
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - "8000:8000"
    environment:
      - QBITTORRENT_HOST=qbittorrent
      - QBITTORRENT_PORT=8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=adminadmin
    env_file:
      - ./config/scraper.env
    depends_on:
      - qbittorrent

  gotify:
    image: gotify/server
    ports:
      - "8080:80"
    volumes:
      - ./data/gotify/data:/app/data

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ./data/qbittorrent/config:/config
      - ./downloads:/downloads
    ports:
      - "8081:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
